services:
-   type: web
    name: bp_test
    runtime: node
    repo: https://github.com/alexwbi88/express-test-prpreview
    # scaling:
      # minInstances: 1
      # maxInstances: 3
      # targetMemoryPercent: 60 # optional if targetCPUPercent is set
      # targetCPUPercent: 60 # optional if targetMemory is set
    buildCommand: yarn
    startCommand: node app.js
    plan: free
    autoDeploy: false # optional
databases:
  - name: t4
    databaseName: mydb # optional (Render may add a suffix)
    user: adrian # optional
